### ISSUE TITLE
[Feat] 프론트 : 스터디 페이지

### ISSUE THREAD

**Issue by gminnimk** [StUdY-TrEk/Boot-Camping#12]
**⭐ Issue : Feature**
프론트 : 리뷰 페이지 제작

**Description**
스터디 UI/UX

**Todo**
- [x] 스터디 메인(조회) 페이지
- [x] 스터디 작성 페이지
- [x] 스터디 상세 페이지
- [x] 스터디 수정 페이지
- [ ] 백엔드 연동

**Reference(Optional) **
참고 사항이 있다면 작성해주세요
