### ISSUE TITLE
[Feat] 프론트 : 부트캠프 모집글 페이지

### ISSUE THREAD

**Issue by hgi4657** [StUdY-TrEk/Boot-Camping#7]
**⭐ Issue : Feature**
프론트 : 부트캠프 모집글 페이지

**Description**
부트캠프 UI/UX

**Todo**
- [x] 모집글 메인 페이지
- [x] 모집글 상세 페이지
- [x] 모집글 작성 페이지
- [x] 백엔드 연동

**Reference(Optional) **
부트 캠프 모집글에 존재하는 좋아요 버튼 (개수 +누른 표시)
